### PR TITLE
rtic-syntax: v1.0.3 prep

### PR DESCRIPTION
**Pull request by AfoHT**

### CODE REVIEW

**Review by korken89 — DISMISSED** [review]
bors merge

**Comment by korken89** [comment]
bors cancel

**Review by korken89 — DISMISSED** [review]
bors merge

**Comment by korken89** [comment]
bors cancel

**Review by perlindgren — APPROVED** [review]
bors +

**Review by perlindgren — APPROVED** [review]
bors merge

**Pull request merged**
