### PR TITLE
Fix `Does not compile using the latest nightly #7`

### LINKED ISSUE #7: Does not compile using the latest nightly
```
james@archx1cv4r2 ➜  rtfm-syntax git:(master) cargo build
    Updating registry `https://github.com/rust-lang/crates.io-index`
 Downloading syn v0.13.11                                                       
 Downloading backtrace v0.3.8                                                   
 Downloading backtrace-sys v0.1.19                                              
 Downloading libc v0.2.41                                                       
   Compiling unicode-xid v0.0.4                                                 
   Compiling cc v1.0.15
   Compiling quote v0.3.15
   Compiling unicode-xid v0.1.0
   Compiling libc v0.2.41
   Compiling rustc-demangle v0.1.8
   Compiling cfg-if v0.1.3
   Compiling either v1.5.0
   Compiling synom v0.11.3
   Compiling proc-macro2 v0.3.8
   Compiling syn v0.11.11
error[E0433]: failed to resolve. Could not find `Op` in `proc_macro`
   --> /home/james/.cargo/registry/src/github.com-1ecc6299db9ec823/proc-macro2-0.3.8/src/unstable.rs:131:42
    |
131 |                 let mut op = proc_macro::Op::new(tt.op(), spacing);
    |                                          ^^ Could not find `Op` in `proc_macro`

error[E0433]: failed to resolve. Could not find `Term` in `proc_macro`
   --> /home/james/.cargo/registry/src/github.com-1ecc6299db9ec823/proc-macro2-0.3.8/src/unstable.rs:446:59
    |
446 |             Span::Nightly(s) => Term::Nightly(proc_macro::Term::new(string, s)),
    |                                                           ^^^^ Could not find `Term` in `proc_macro`

error[E0412]: cannot find type `Term` in module `proc_macro`
   --> /home/james/.cargo/registry/src/github.com-1ecc6299db9ec823/proc-macro2-0.3.8/src/unstable.rs:439:25
    |
439 |     Nightly(proc_macro::Term),
    |                         ^^^^ not found in `proc_macro`
help: possible candidates are found in other modules, you can import them into scope
    |
3   | use Term;
    |
3   | use imp::Term;
    |
3   | use stable::Term;
    |

error[E0412]: cannot find type `Term` in module `proc_macro`
   --> /home/james/.cargo/registry/src/github.com-1ecc6299db9ec823/proc-macro2-0.3.8/src/unstable.rs:473:44
    |
473 |     fn unwrap_nightly(self) -> proc_macro::Term {
    |                                            ^^^^ not found in `proc_macro`
help: possible candidates are found in other modules, you can import them into scope
    |
3   | use Term;
    |
3   | use imp::Term;
    |
3   | use stable::Term;
    |

error[E0599]: no variant named `Op` found for type `proc_macro::TokenTree` in the current scope
   --> /home/james/.cargo/registry/src/github.com-1ecc6299db9ec823/proc-macro2-0.3.8/src/unstable.rs:228:13
    |
228 |             proc_macro::TokenTree::Op(tt) => {
    |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ variant not found in `proc_macro::TokenTree`

error[E0599]: no variant named `Term` found for type `proc_macro::TokenTree` in the current scope
   --> /home/james/.cargo/registry/src/github.com-1ecc6299db9ec823/proc-macro2-0.3.8/src/unstable.rs:237:13
    |
237 |             proc_macro::TokenTree::Term(s) => ::Term::_new(Term::Nightly(s)).into(),
    |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ variant not found in `proc_macro::TokenTree`

error: aborting due to 6 previous errors

Some errors occurred: E0412, E0433, E0599.
For more information about an error, try `rustc --explain E0412`.
error: Could not compile `proc-macro2`.
warning: build failed, waiting for other jobs to finish...
error: build failed
```

### PR DESCRIPTION
**Pull request by fmckeogh**
I bumped dependencies and added new `proc-macro2` syntax. I don't think what I wrote is best practice though :(

Fixes #7

### CODE REVIEW

**Comment by fmckeogh** [comment]
I think similar fixes are required for `cortex-m-rtfm-macros`, but seem a bit more in depth. Dependency bumps will then be required for quite a few crates.

**Comment by et1975** [comment]
In the meanwhile, is there a workaround?

**Comment by fmckeogh** [comment]
@et1975 You can add my fork to your Cargo.toml as a git crate. I think you might have to use the second to last commit as the latest will not build locally.

**Comment by et1975** [comment]
@chocol4te thanks, had to [tweak it](/et1975/cortex-m-rtfm), if anyone needs this.

**Comment by bergus** [comment]
@japaric Can you merge this?

**Comment by bergus** [comment]
@chocol4te I've successfully used your version with the latest nightly, the necessary updates for `cortext-m-rtfm-macros` can be found in [this commit](https://github.com/japaric/cortex-m-rtfm/pull/78/commits/ca1af7feab23005e597e94567a825e513c353796).

**Comment by chocol4te** [comment]
@bergus Should I close this PR then?

**Comment by japaric** [comment]
@chocol4te Thanks!

bors r+

**Pull request merged**
