### PR TITLE
CI: replace compiletest with trybuild

### PR DESCRIPTION
**Pull request by japaric**
in the same vein as rtfm-rs/cortex-m-rtfm#268

### CODE REVIEW

**Comment by japaric** [comment]
bors try

**Review by perlindgren — DISMISSED** [review]

**Review by perlindgren — APPROVED** [review]
bors +

**Comment by perlindgren** [comment]
bors +

**Comment by perlindgren** [comment]
bors +

**Comment by japaric** [comment]
bors r=perlindgren

**Pull request merged**
